name: Tests

on: [ push, pull_request ]

jobs:
  tests:
    name: "Tests"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
        typo3-version:
          - "^9.5"
          - "^10.4"
          - "^11.5"
          - "^12.0"
        composer-flags:
          - ""
          - " --prefer-lowest"
        exclude:
          - php-version: "8.0"
            typo3-version: "^9.5"
          - php-version: "8.1"
            typo3-version: "^9.5"
          - php-version: "8.0"
            typo3-version: "^10.4"
          - php-version: "8.1"
            typo3-version: "^10.4"
          - php-version: "7.4"
            typo3-version: "^12.0"
          - php-version: "8.0"
            typo3-version: "^12.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress ${{ matrix.composer-flags }}"

      - name: "Install specific typo3 version"
        run: "composer update --no-interaction --no-progress --with typo3/cms-core:${{ matrix.typo3-version }}"

      - name: "Tests"
        run: |
          vendor/bin/phing
